###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "email": "wehbvcmsehvewhflrz@sdvrecft.com",
    "password": "thunder",
    "roles": ["KHACH_HANG"]
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "rxtk5ypwwb@email.edu.pl",
    "password": "thunder"
}
