###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "email": "iqe72956@cuoly.com",
    "password": "thunder",
    "roles": ["KHACH_HANG"]
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "iqe72956@cuoly.com",
    "password": "thunder"
}