###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "email": "5ozcr0u4bs@email.edu.pl",
    "password": "123456789",
    "roles": ["KHACH_HANG"]
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "h2z4ld87m3@eposta.buzz",
    "password": "Thunder123"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "trisnguyen25112000@gmail.com",
    "password": "123456789"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "covid21tsp@gmail.com",
    "password": "123456789"
}
