###
POST http://localhost:5000/api/bookingdetail/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTEyMzk0YmJiOGZjY2U2OTE0MmIiLCJyb2xlcyI6WyJLSEFDSF9IQU5HIiwiQ0hVX1NBTiJdLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjM3NzI0NTg5LCJleHAiOjE2Mzc4MTA5ODl9.xcqz_zVr5RLs1DtUA5uszpwOCdXMMtt_FefBFR8BFGk
Content-Type: application/json

{
    "startTime": "12/11/2023 00:00",
    "endTime": "12/11/2023 02:00",
    "price": 200000,
    "status": "619dbcd8bc930d10be70a610",
    "booking": "619db648aef5c6de617106ee",
    "pitch":"619bb2791637cd9082f29adb"
}

{
        "startTime": "12/11/2023 00:00",
        "endTime": "12/11/2023 02:00",
        "status": "619dbcd8bc930d10be70a610",
}

###
POST http://localhost:5000/api/bookingdetail/pitchType
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTEyMzk0YmJiOGZjY2U2OTE0MmIiLCJyb2xlcyI6WyJLSEFDSF9IQU5HIiwiQ0hVX1NBTiJdLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjM3NzI0NTg5LCJleHAiOjE2Mzc4MTA5ODl9.xcqz_zVr5RLs1DtUA5uszpwOCdXMMtt_FefBFR8BFGk
Content-Type: application/json

{
    "startTime": "12/11/2023 07:30",
    "endTime": "12/11/2023 08:00",
    "price": 200000,
    "status": "619dbcd8bc930d10be70a610",
    "booking": "619db648aef5c6de617106ee",
    "pitchType":"619bb3e1b770e45c464db6e2"
}
###

GET http://localhost:5000/api/bookingdetail/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTkxZWNmYjI5ZTQ1ZmNmZTc3N2M0NzgiLCJyb2xlcyI6WyJLSEFDSF9IQU5HIiwiQ0hVX1NBTiJdLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjM3MzA3NDkyLCJleHAiOjE2MzczMTEwOTJ9.v6wV0EK77TLhFo89riXlEOIrLPb1AqEQ9agvZ49QVGg

###
GET http://localhost:5000/api/bookingdetail/bookedTime?pitch=61a1089dc0e40d948fdf9b2e

###
{
    [
        date: "12/11/2023",
        time: [
            {
                startTime: "00:00",
                endTime: "02:00"
            },
            {
                startTime: "00:00",
                endTime: "02:00"
            }
        ]
    ],
    [
        date: "12/11/2023",
        time: [
            {
                startTime: "00:00",
                endTime: "02:00"
            },
            {
                startTime: "00:00",
                endTime: "02:00"
            }
        ]
    ],

}