POST http://localhost:5000/api/booking
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTIxM2E2YzhmNzIzOWVlMWYxNjkiLCJyb2xlcyI6WyJDSFVfU0FOIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2Mzc3MzAxMTUsImV4cCI6MTYzNzgxNjUxNX0.-y2F9fRuFjD7p057qAFLWoQeyxZXMOTfbpBxqO8UNnk
Content-Type: application/json

{
    "startDate": "11/12/2023",
    "endDate": "29/12/2023",
    "total": "20000000",
    "isPaid": true,
    "customer": "619ba213a6c8f7239ee1f169"

}

### //check booking
{
        "startTime": "12/11/2023 00:00",
        "endTime": "12/11/2023 02:00",
        "customer": "619ba213a6c8f7239ee1f169",
        "pitch":"619bb2791637cd9082f29adb"
}

### //  booking confirm
POST http://localhost:5000/api/booking/confirm
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWFmNjE3YTFhMWRkYzZjNWEwYjZmYWMiLCJyb2xlcyI6WyJLSEFDSF9IQU5HIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzkwMjEzNjMsImV4cCI6MTYzOTEwNzc2M30.L0LiqkrJ5vlwKJi5iehSv8TCh8CyDcOHK81OUcAJOEQ
Content-Type: application/json

{
        "startTime": "10/12/2021 08:30",
        "endTime": "10/12/2021 09:00",
        "status": "ST1",
        "isPaid": true,
        "name": "",
        "phone": "",
        "customer": "61af617a1a1ddc6c5a0b6fac",
        "pitch":"61a1089dc0e40d948fdf9b2e"
}

###

POST http://localhost:5000/api/booking/checkout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWFmNjE3YTFhMWRkYzZjNWEwYjZmYWMiLCJyb2xlcyI6WyJLSEFDSF9IQU5HIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2Mzg5Nzg4NDksImV4cCI6MTYzOTA2NTI0OX0.pMiEKnlDLEXJKf5VcEFK2_lqF9mizt-zHSdBWEXXlhQ
Content-Type: application/json

{
    "startTime": "11/12/2021 12:30",
    "endTime": "11/12/2021 13:00",
    "pitch":"619bb432b770e45c464db6ec"
    //"customer": "619ba12394bbb8fcce69142b",
}
 
###
GET http://localhost:5000/api/booking
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliOWQ2MjgyOGMwYWQ2YjQ4YWM1ZmQiLCJyb2xlcyI6WyJBRE1JTiJdLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2Mzg2ODEzNDEsImV4cCI6MTYzODc2Nzc0MX0.q3VX4o1IEGCvz30OWpNNW9Ec8DytV15PzolYEOSMI2E

###
GET http://localhost:5000/api/booking?customerId=61af617a1a1ddc6c5a0b6fac
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWFmNjE3YTFhMWRkYzZjNWEwYjZmYWMiLCJyb2xlcyI6WyJLSEFDSF9IQU5HIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2Mzg5NzYwOTUsImV4cCI6MTYzOTA2MjQ5NX0.n0bKoAphj-l4TsD5hnXODSKWwB93qAbGE3lBx8O4gY8

###
GET http://localhost:5000/api/booking?pitchBranchId=619ba93bba72b12e6ea9f2f6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTIxM2E2YzhmNzIzOWVlMWYxNjkiLCJyb2xlcyI6WyJDSFVfU0FOIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2Mzg2ODUwMTIsImV4cCI6MTYzODc3MTQxMn0.ySgLdEUUE0GFPYs7r-3BTczwPbl5BiFCa-NoHqATUo8

###
GET http://localhost:5000/api/booking
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliOWQ2MjgyOGMwYWQ2YjQ4YWM1ZmQiLCJyb2xlcyI6WyJBRE1JTiJdLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2Mzg2ODU1NjYsImV4cCI6MTYzODc3MTk2Nn0.CAbWvxZ0-MLIyS4-EY_9LyAYdxDUS0RdQ1SQbyVl7Aw

###
GET http://localhost:5000/api/booking/619743880b34ce1c4b933c59
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThlMGM1MmEwYjc2ZjY3N2U1ODdlMzgiLCJyb2xlcyI6WyJBRE1JTiIsIktIQUNIX0hBTkciLCJDSFVfU0FOIl0sImlzQWRtaW4iOnRydWUsImlhdCI6MTYzNzMwMjg3OCwiZXhwIjoxNjM3MzA2NDc4fQ.qXlYfxdvPJqgcwBEka0bvBU52JKiOnZwKQzfYpMcdhM

###
PUT http://localhost:5000/api/booking/619743880b34ce1c4b933c59
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThlMGM1MmEwYjc2ZjY3N2U1ODdlMzgiLCJyb2xlcyI6WyJBRE1JTiIsIktIQUNIX0hBTkciLCJDSFVfU0FOIl0sImlzQWRtaW4iOnRydWUsImlhdCI6MTYzNzMwMjg3OCwiZXhwIjoxNjM3MzA2NDc4fQ.qXlYfxdvPJqgcwBEka0bvBU52JKiOnZwKQzfYpMcdhM
Content-Type: application/json

{
    "startDate": "20/11",
    "endDate": "20/11",
    "total": "30000000",
    "isPaid": true,
    "customer": "6191ecfb29e45fcfe777c478"
}

###
PUT http://localhost:5000/api/booking/checkin/9f5cf7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTIxM2E2YzhmNzIzOWVlMWYxNjkiLCJyb2xlcyI6WyJDSFVfU0FOIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzkwNTQzMDgsImV4cCI6MTYzOTE0MDcwOH0.bINwOUJW0NtgToXDA2rf7-bewQdj8s5QHkeiwaaDU4s

###
PUT http://localhost:5000/api/booking/cancel/61a363d45f845dbff84c088d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTIxM2E2YzhmNzIzOWVlMWYxNjkiLCJyb2xlcyI6WyJDSFVfU0FOIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzkwNTQzMDgsImV4cCI6MTYzOTE0MDcwOH0.bINwOUJW0NtgToXDA2rf7-bewQdj8s5QHkeiwaaDU4s
Content-Type: application/json

{
    "status": "ST3"
}

###
DELETE http://localhost:5000/api/booking/61974575a491e8f384c7cf35
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThlMGM1MmEwYjc2ZjY3N2U1ODdlMzgiLCJyb2xlcyI6WyJBRE1JTiIsIktIQUNIX0hBTkciLCJDSFVfU0FOIl0sImlzQWRtaW4iOnRydWUsImlhdCI6MTYzNzMwMjg3OCwiZXhwIjoxNjM3MzA2NDc4fQ.qXlYfxdvPJqgcwBEka0bvBU52JKiOnZwKQzfYpMcdhM

###
GET http://localhost:5000/api/booking
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliOWQ2MjgyOGMwYWQ2YjQ4YWM1ZmQiLCJyb2xlcyI6WyJBRE1JTiJdLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2MzgyNTE2MDYsImV4cCI6MTYzODMzODAwNn0.C408BlD8izoV-UmjCpiH2c1POBSJnWKM2bZc3Vzy23k

###
PUT http://localhost:5000/api/booking/refresh/619ba93bba72b12e6ea9f2f6

###
GET http://localhost:5000/api/booking/static
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTIxM2E2YzhmNzIzOWVlMWYxNjkiLCJyb2xlcyI6WyJDSFVfU0FOIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzkwMzkxOTQsImV4cCI6MTYzOTEyNTU5NH0.VbD4_YwwwG2-HEkDkV0pK2ib8PEvltu1PrHMHfHz7TU
Content-Type: application/json

{
    "startDate": "12/10/2023",
    "endDate": "31/12/2023",
    "pitchBranchId": "619ba93bba72b12e6ea9f2f6"
}

###
GET http://localhost:5000/api/booking/static?startDate=12/10/2020&endDate=31/12/2023&pitchBranchId=619ba93bba72b12e6ea9f2f6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliOWQ2MjgyOGMwYWQ2YjQ4YWM1ZmQiLCJyb2xlcyI6WyJBRE1JTiJdLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2MzkwMzk0MTcsImV4cCI6MTYzOTEyNTgxN30.HxtR9KOHQ6OKmG2v3F2QNICSVmFATTLWlRkXKqMR9PU

###
GET http://localhost:5000/api/booking/static?startDate=12/10/2023&endDate=31/12/2023
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliOWQ2MjgyOGMwYWQ2YjQ4YWM1ZmQiLCJyb2xlcyI6WyJBRE1JTiJdLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2Mzg2OTE0NTQsImV4cCI6MTYzODc3Nzg1NH0.-Ew-Mu-_0CrPV3uXetDPPep3kRhzhSz3pwxKwB1NHf0