### // Tạo account
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "email": "5ozcr0u4bs@email.edu.pl",
    "password": "123456789",
    "roles": ["KHACH_HANG"]
}

### // Đăng nhập
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "ngoctinh3004@gmail.com",
    "password": "thunder"
}

### // Tạo chi nhánh sân
POST http://localhost:5000/api/pitchBranch
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTIxM2E2YzhmNzIzOWVlMWYxNjkiLCJyb2xlcyI6WyJDSFVfU0FOIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2Mzc5MzgzNTAsImV4cCI6MTYzODAyNDc1MH0.qS_jx0Eap3MssAtmjE725MajkXj982fpffy5c2ljo6M
Content-Type: application/json

{
    "displayName": "Sân ba bà Ba",
    "phoneNumber": "0987654321",
    "address": "số 113",
    "ward": "phường 4",
    "district": "quận 3",
    "province": "TP.HCM",
    "description":"đá banh đá bóng nè",
    "startTime": "07:00",
    "endTime": "23:00",
    "owner": "619ba213a6c8f7239ee1f169"
}

### // Tạo loại sân
POST http://localhost:5000/api/pitchtype
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTIxM2E2YzhmNzIzOWVlMWYxNjkiLCJyb2xlcyI6WyJDSFVfU0FOIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2Mzc5MzgzNTAsImV4cCI6MTYzODAyNDc1MH0.qS_jx0Eap3MssAtmjE725MajkXj982fpffy5c2ljo6M
Content-Type: application/json

{
    "displayName": "Sân 5",
    "description": "Sân này có 5 người",
    "pitchBranch":"619ba93bba72b12e6ea9f2f6"
}

### // Tạo sân
POST http://localhost:5000/api/pitch
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTIxM2E2YzhmNzIzOWVlMWYxNjkiLCJyb2xlcyI6WyJDSFVfU0FOIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2Mzc5MzgzNTAsImV4cCI6MTYzODAyNDc1MH0.qS_jx0Eap3MssAtmjE725MajkXj982fpffy5c2ljo6M
Content-Type: application/json

{
    "displayName": "Sân 5 đứa nhỏ",
    "description": "Sân này thích cho con ních đá hơn",
    "pitchType": "61a1083bc0e40d948fdf9b29"
}

### // Thêm giá cho sân
###
POST http://localhost:5000/api/price
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTIxM2E2YzhmNzIzOWVlMWYxNjkiLCJyb2xlcyI6WyJDSFVfU0FOIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2Mzc1OTUyNTIsImV4cCI6MTYzNzY4MTY1Mn0.fNHwSsJOuTVMOVddqnFbvXDcyfPflkwWtSBk5xsMpjQ
Content-Type: application/json

{
    "pitchType": "619ba88fc99ae8e7b202c0cd",
    "time": "619ba8d7c99ae8e7b202c0ef",
    "price": "10000"
}

### // Khách hàng xem tất cả các chi nhánh 
GET http://localhost:5000/api/pitchBranch
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTEyMzk0YmJiOGZjY2U2OTE0MmIiLCJyb2xlcyI6WyJLSEFDSF9IQU5HIiwiQ0hVX1NBTiJdLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjM3OTEwNDA1LCJleHAiOjE2Mzc5OTY4MDV9.VCibm94G1frWFt3QDqVmP9HvB8yT3xrjXHhu_LErPLw


### // Khách hàng xem tất cả sân theo chi nhánh
GET http://localhost:5000/api/pitchBranch/getDetail/619ba93bba72b12e6ea9f2f6

### // khách hàng kiểm tra sân
POST http://localhost:5000/api/booking/checkout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTIxM2E2YzhmNzIzOWVlMWYxNjkiLCJyb2xlcyI6WyJDSFVfU0FOIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2Mzg4NjA2NTQsImV4cCI6MTYzODk0NzA1NH0.qOs3tz6G7h9ozUxglIGLoR2PtWM5QmqtACuxERIK0MU
Content-Type: application/json

{
    "startTime": "08/12/2023 18:00",
    "endTime": "08/12/2023 19:30",
    "pitch":"619bb432b770e45c464db6ec"
}

### // khách hàng đặt sân
POST http://localhost:5000/api/booking/confirm
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTEyMzk0YmJiOGZjY2U2OTE0MmIiLCJyb2xlcyI6WyJLSEFDSF9IQU5HIiwiQ0hVX1NBTiJdLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjM3OTEwNDA1LCJleHAiOjE2Mzc5OTY4MDV9.VCibm94G1frWFt3QDqVmP9HvB8yT3xrjXHhu_LErPLw
Content-Type: application/json

{
        "startTime": "12/11/2023 07:30",
        "endTime": "12/11/2023 08:30",
        "status": "ST1",
        "isPaid": true,
        "customer": "619ba12394bbb8fcce69142b",
        "pitch":"619bb43bb770e45c464db6f1"
}

### // khách hàng đến và check in sân
###
PUT http://localhost:5000/api/booking/checkin/fc8b90
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTIxM2E2YzhmNzIzOWVlMWYxNjkiLCJyb2xlcyI6WyJDSFVfU0FOIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2Mzc5MzgzNTAsImV4cCI6MTYzODAyNDc1MH0.qS_jx0Eap3MssAtmjE725MajkXj982fpffy5c2ljo6M
Content-Type: application/json

{
    "status": "ST2"
}

### // xem lịch sử đặt sân của khách hàng
GET http://localhost:5000/api/booking?customerId=619ba12394bbb8fcce69142b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTEyMzk0YmJiOGZjY2U2OTE0MmIiLCJyb2xlcyI6WyJLSEFDSF9IQU5HIiwiQ0hVX1NBTiJdLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjM3OTEwNDA1LCJleHAiOjE2Mzc5OTY4MDV9.VCibm94G1frWFt3QDqVmP9HvB8yT3xrjXHhu_LErPLw


### // xem lịch sử đặt sân của id chi nhánh
GET http://localhost:5000/api/booking?pitchBranchId=619ba93bba72b12e6ea9f2f6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTIxM2E2YzhmNzIzOWVlMWYxNjkiLCJyb2xlcyI6WyJDSFVfU0FOIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2Mzc5MzgzNTAsImV4cCI6MTYzODAyNDc1MH0.qS_jx0Eap3MssAtmjE725MajkXj982fpffy5c2ljo6M

