POST http://localhost:5000/api/pitch
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTE4M2E2YzhmNzIzOWVlMWYxNjIiLCJyb2xlcyI6WyJDSFVfU0FOIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2Mzg2NzkyMjgsImV4cCI6MTYzODc2NTYyOH0._HbBDfyhF3QHjminiig-AcPZcBtsX7WjYPHIHbm4x8c
Content-Type: application/json

{
    "displayName": "Sân ba đưa đá",
    "description": "Sân này thích cho con ních đá cho zui",
    "pitchType": "61ac4344a893a586fc58d595"

}

###
GET http://localhost:5000/api/pitch
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTkxZWNmYjI5ZTQ1ZmNmZTc3N2M0NzgiLCJyb2xlcyI6WyJLSEFDSF9IQU5HIiwiQ0hVX1NBTiJdLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjM3MTI5NzM0LCJleHAiOjE2MzcxMzMzMzR9.iCXmDVV8ypGud1pdvtGsgA5jKbAk0AByzrluim9KHWA

###
GET http://localhost:5000/api/pitch/619b19bbf90f2bb8d1bf4267
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTkxZWNmYjI5ZTQ1ZmNmZTc3N2M0NzgiLCJyb2xlcyI6WyJLSEFDSF9IQU5HIiwiQ0hVX1NBTiJdLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjM3NTU0MzkwLCJleHAiOjE2Mzc1NTc5OTB9._KUUz8sE4Ju1q7kbIz-eQgfTRIcrchHsM2sDdAkHknk

###
PUT http://localhost:5000/api/pitch/619bb432b770e45c464db6ec
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTIxM2E2YzhmNzIzOWVlMWYxNjkiLCJyb2xlcyI6WyJDSFVfU0FOIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzkyMzM5MjcsImV4cCI6MTYzOTMyMDMyN30.vnfuQATZ22IsTa7cOdOZHKT0wGydmo2ZOPqVHbN3hFA
Content-Type: application/json

{
    "isActive": true
}

###
DELETE http://localhost:5000/api/pitch/61a1089dc0e40d948fdf9b2e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTIxM2E2YzhmNzIzOWVlMWYxNjkiLCJyb2xlcyI6WyJDSFVfU0FOIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2Mzk0MDU1MDEsImV4cCI6MTYzOTQ5MTkwMX0.7fISiyz7UNBWY4v_WXOGlZ1crpCwce7_lDPioWhIeZs

###
GET http://localhost:5000/api/pitch?pitchType=61975db55189c10b99d74068
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTIxM2E2YzhmNzIzOWVlMWYxNjkiLCJyb2xlcyI6WyJDSFVfU0FOIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2Mzk0MDU1MDEsImV4cCI6MTYzOTQ5MTkwMX0.7fISiyz7UNBWY4v_WXOGlZ1crpCwce7_lDPioWhIeZs



