POST http://localhost:5000/api/pitch
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTIxM2E2YzhmNzIzOWVlMWYxNjkiLCJyb2xlcyI6WyJDSFVfU0FOIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2Mzc1OTQwMDQsImV4cCI6MTYzNzY4MDQwNH0.9yWJsC59unFc9Qz6dKtc7qCkE6XgkypDSCwqi1cbOSo
Content-Type: application/json

{
    "displayName": "Sân bờ hồ Hoàng Gia",
    "description": "Sân này kế bên sông",
    "pitchType": "619bb3e9b770e45c464db6e7"

}

###
GET http://localhost:5000/api/pitch
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTkxZWNmYjI5ZTQ1ZmNmZTc3N2M0NzgiLCJyb2xlcyI6WyJLSEFDSF9IQU5HIiwiQ0hVX1NBTiJdLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjM3MTI5NzM0LCJleHAiOjE2MzcxMzMzMzR9.iCXmDVV8ypGud1pdvtGsgA5jKbAk0AByzrluim9KHWA

###
GET http://localhost:5000/api/pitch/619b19bbf90f2bb8d1bf4267
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTkxZWNmYjI5ZTQ1ZmNmZTc3N2M0NzgiLCJyb2xlcyI6WyJLSEFDSF9IQU5HIiwiQ0hVX1NBTiJdLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjM3NTU0MzkwLCJleHAiOjE2Mzc1NTc5OTB9._KUUz8sE4Ju1q7kbIz-eQgfTRIcrchHsM2sDdAkHknk

###
PUT http://localhost:5000/api/pitch/619b19bbf90f2bb8d1bf4267
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTkxZWNmYjI5ZTQ1ZmNmZTc3N2M0NzgiLCJyb2xlcyI6WyJLSEFDSF9IQU5HIiwiQ0hVX1NBTiJdLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjM3NTU0MzkwLCJleHAiOjE2Mzc1NTc5OTB9._KUUz8sE4Ju1q7kbIz-eQgfTRIcrchHsM2sDdAkHknk
Content-Type: application/json

{
    "displayName": "Sân C rồi",
    "description": "Sân này kế cây bự á",
    "pitchType": "61975db55189c10b99d74068"
}

###
DELETE http://localhost:5000/api/pitch/619b19bbf90f2bb8d1bf424
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTkxZWNmYjI5ZTQ1ZmNmZTc3N2M0NzgiLCJyb2xlcyI6WyJLSEFDSF9IQU5HIiwiQ0hVX1NBTiJdLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjM3NTU0MzkwLCJleHAiOjE2Mzc1NTc5OTB9._KUUz8sE4Ju1q7kbIz-eQgfTRIcrchHsM2sDdAkHknk

###
GET http://localhost:5000/api/pitch?pitchType=61975db55189c10b99d74068
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTkxZWNmYjI5ZTQ1ZmNmZTc3N2M0NzgiLCJyb2xlcyI6WyJLSEFDSF9IQU5HIiwiQ0hVX1NBTiJdLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjM3NTU3NTgwLCJleHAiOjE2Mzc1NjExODB9.kK_ZVS9OKqwawR1oqGlM_UqxxWotF4vp1W3JixXjKqc



