###
GET http://localhost:5000/api/pitchtype
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThlMGM1MmEwYjc2ZjY3N2U1ODdlMzgiLCJyb2xlcyI6WyJBRE1JTiIsIktIQUNIX0hBTkciLCJDSFVfU0FOIl0sImlzQWRtaW4iOnRydWUsImlhdCI6MTYzNzA0MDQwMCwiZXhwIjoxNjM3MDQ0MDAwfQ.y_JLPRS2mB1z3BPaILCTvJToDb6I97WydqGtL97juDs

###
POST http://localhost:5000/api/pitchtype
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTIxM2E2YzhmNzIzOWVlMWYxNjkiLCJyb2xlcyI6WyJDSFVfU0FOIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzkwNTQzMDgsImV4cCI6MTYzOTE0MDcwOH0.bINwOUJW0NtgToXDA2rf7-bewQdj8s5QHkeiwaaDU4s
Content-Type: application/json

{
    "displayName": "Sân bỏ",
    "description": "Sân này có 5 người",
    "pitchBranch":"619ba93bba72b12e6ea9f2f6"
}

###
PUT http://localhost:5000/api/pitchtype/6190cf8840851e03ca987d2a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThlMGM1MmEwYjc2ZjY3N2U1ODdlMzgiLCJyb2xlcyI6WyJBRE1JTiIsIktIQUNIX0hBTkciLCJDSFVfU0FOIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzcwMzk2MzAsImV4cCI6MTYzNzA0MzIzMH0.tgnNMXyAkp6jB9kAjXAXCKdqkXr21eytUrrA986m0Vg
Content-Type: application/json

{
    "displayName": "Sân 11",
    "description": "Sân này có 11 người",
    "pitchBranch":"6191ee94a487c92bab48d44e"
}

###
DELETE http://localhost:5000/api/pitchtype/619bb3e1b770e45c464db6e2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTIxM2E2YzhmNzIzOWVlMWYxNjkiLCJyb2xlcyI6WyJDSFVfU0FOIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2Mzk0MDU1MDEsImV4cCI6MTYzOTQ5MTkwMX0.7fISiyz7UNBWY4v_WXOGlZ1crpCwce7_lDPioWhIeZs

###
GET http://localhost:5000/api/pitchtype/6190cf8840851e03ca987d2a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTIxM2E2YzhmNzIzOWVlMWYxNjkiLCJyb2xlcyI6WyJDSFVfU0FOIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2Mzk0MDU1MDEsImV4cCI6MTYzOTQ5MTkwMX0.7fISiyz7UNBWY4v_WXOGlZ1crpCwce7_lDPioWhIeZs

###
GET http://localhost:5000/api/pitchtype?branchId=6191ee94a487c92bab48d44e&Bra=123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTkxZWNmYjI5ZTQ1ZmNmZTc3N2M0NzgiLCJyb2xlcyI6WyJLSEFDSF9IQU5HIiwiQ0hVX1NBTiJdLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjM3MTM3OTYyLCJleHAiOjE2MzcxNDE1NjJ9.RTbcZfN5VYZT2MutEh8M9iTzFJDQLN1Wy9IqmOaOoys
