###
baba
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTIxM2E2YzhmNzIzOWVlMWYxNjkiLCJyb2xlcyI6WyJDSFVfU0FOIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2Mzc1OTQwMDQsImV4cCI6MTYzNzY4MDQwNH0.9yWJsC59unFc9Qz6dKtc7qCkE6XgkypDSCwqi1cbOSo
tris
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTEyMzk0YmJiOGZjY2U2OTE0MmIiLCJyb2xlcyI6WyJLSEFDSF9IQU5HIiwiQ0hVX1NBTiJdLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjM3NTkzMTY2LCJleHAiOjE2Mzc2Nzk1NjZ9.zrhNJOKqnVD3aiKSYi9NmryDKNgRg0ivi_-hRBpOtaA
###
POST http://localhost:5000/api/price
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTIxM2E2YzhmNzIzOWVlMWYxNjkiLCJyb2xlcyI6WyJDSFVfU0FOIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzkyNDI5MDYsImV4cCI6MTYzOTMyOTMwNn0.e72iRsH5auPmbPaK6lvS1QBXJk6BlDDzSpLZbIDTO3w
Content-Type: application/json

{
    "pitchType": "61a1083bc0e40d948fdf9b29",
    "time": "619ba8d6c99ae8e7b202c0d9",
    "price": "10000"
}

###

GET http://localhost:5000/api/price
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThlMGM1MmEwYjc2ZjY3N2U1ODdlMzgiLCJyb2xlcyI6WyJBRE1JTiIsIktIQUNIX0hBTkciLCJDSFVfU0FOIl0sImlzQWRtaW4iOnRydWUsImlhdCI6MTYzNzA1MzUzMywiZXhwIjoxNjM3MDU3MTMzfQ.1u7yKdTv3_hf96SdOr0Kzsvi4JZdY3m8nf5FfQcww_Y

###
GET http://localhost:5000/api/price/6193536844ab97ae11537db7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTkxZWNmYjI5ZTQ1ZmNmZTc3N2M0NzgiLCJyb2xlcyI6WyJLSEFDSF9IQU5HIiwiQ0hVX1NBTiJdLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjM3MDUzNTExLCJleHAiOjE2MzcwNTcxMTF9.5qp6tFAVnmKDGiWG7-izy3WeWQ_-XMNRrl2tV5Y81Io

###
PUT  http://localhost:5000/api/price/619bacdc7eb3c1e90106768a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTIxM2E2YzhmNzIzOWVlMWYxNjkiLCJyb2xlcyI6WyJDSFVfU0FOIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzkyNDE1OTgsImV4cCI6MTYzOTMyNzk5OH0.O6p3b479DeIQ4hD_Bq9x_Z37i9WztyVfd-5KUWn_u5Y
Content-Type: application/json

{
    "pitchType": "61a1083bc0e40d948fdf9b29",
    "time": "619ba8d6c99ae8e7b202c0d3",
    "price": "2000"
}

###
POST http://localhost:5000/api/price/arrtime
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTIxM2E2YzhmNzIzOWVlMWYxNjkiLCJyb2xlcyI6WyJDSFVfU0FOIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2Mzk3NTc1MjMsImV4cCI6MTYzOTg0MzkyM30.7tn5ETd_J3GuOEAJPw7mJWmh8WRAGhSbYS2zSpXu2tM
Content-Type: application/json

{
    "pitchType": "61b8473074e9f32b175bddcb",
    "prices":[
        {
            "startTime": "00:30",
            "endTime": "01:30",
            "price": "100000"
        },
        {
            "startTime": "01:30",
            "endTime": "22:00",
            "price": "120000"
        }
    ]
}

###
DELETE  http://localhost:5000/api/price/619bacdc7eb3c1e90106768a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTIxM2E2YzhmNzIzOWVlMWYxNjkiLCJyb2xlcyI6WyJDSFVfU0FOIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2Mzc1OTUyNTIsImV4cCI6MTYzNzY4MTY1Mn0.fNHwSsJOuTVMOVddqnFbvXDcyfPflkwWtSBk5xsMpjQ

###
GET  http://localhost:5000/api/price
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThlMGM1MmEwYjc2ZjY3N2U1ODdlMzgiLCJyb2xlcyI6WyJBRE1JTiIsIktIQUNIX0hBTkciLCJDSFVfU0FOIl0sImlzQWRtaW4iOnRydWUsImlhdCI6MTYzNzE0MDA4MSwiZXhwIjoxNjM3MTQzNjgxfQ.e25-MLU4PhZ7uox8ZqVZf7lXRKSj5IcRoHcnPMzDWaE


