###
baba
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTIxM2E2YzhmNzIzOWVlMWYxNjkiLCJyb2xlcyI6WyJDSFVfU0FOIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2Mzc1OTQwMDQsImV4cCI6MTYzNzY4MDQwNH0.9yWJsC59unFc9Qz6dKtc7qCkE6XgkypDSCwqi1cbOSo
tris
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTEyMzk0YmJiOGZjY2U2OTE0MmIiLCJyb2xlcyI6WyJLSEFDSF9IQU5HIiwiQ0hVX1NBTiJdLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjM3NTkzMTY2LCJleHAiOjE2Mzc2Nzk1NjZ9.zrhNJOKqnVD3aiKSYi9NmryDKNgRg0ivi_-hRBpOtaA
###
POST http://localhost:5000/api/price
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTIxM2E2YzhmNzIzOWVlMWYxNjkiLCJyb2xlcyI6WyJDSFVfU0FOIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2Mzc1OTUyNTIsImV4cCI6MTYzNzY4MTY1Mn0.fNHwSsJOuTVMOVddqnFbvXDcyfPflkwWtSBk5xsMpjQ
Content-Type: application/json

{
    "pitchType": "619ba88fc99ae8e7b202c0cd",
    "time": "619ba8d7c99ae8e7b202c0ef",
    "price": "10000"
}

###

GET http://localhost:5000/api/price
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThlMGM1MmEwYjc2ZjY3N2U1ODdlMzgiLCJyb2xlcyI6WyJBRE1JTiIsIktIQUNIX0hBTkciLCJDSFVfU0FOIl0sImlzQWRtaW4iOnRydWUsImlhdCI6MTYzNzA1MzUzMywiZXhwIjoxNjM3MDU3MTMzfQ.1u7yKdTv3_hf96SdOr0Kzsvi4JZdY3m8nf5FfQcww_Y

###
GET http://localhost:5000/api/price/6193536844ab97ae11537db7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTkxZWNmYjI5ZTQ1ZmNmZTc3N2M0NzgiLCJyb2xlcyI6WyJLSEFDSF9IQU5HIiwiQ0hVX1NBTiJdLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjM3MDUzNTExLCJleHAiOjE2MzcwNTcxMTF9.5qp6tFAVnmKDGiWG7-izy3WeWQ_-XMNRrl2tV5Y81Io

###
PUT  http://localhost:5000/api/price/619bacdc7eb3c1e90106768a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTIxM2E2YzhmNzIzOWVlMWYxNjkiLCJyb2xlcyI6WyJDSFVfU0FOIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2Mzc1OTUyNTIsImV4cCI6MTYzNzY4MTY1Mn0.fNHwSsJOuTVMOVddqnFbvXDcyfPflkwWtSBk5xsMpjQ
Content-Type: application/json

{
    "pitchType": "6193475a5da96bc6c9721f0a",
    "time": "618f41d01299ceb312bf5cc2",
    "price": "2000"
}

###

{
    "pitchType": "6193475a5da96bc6c9721f0a",
    [
        {
            "startTime": "01:30",
            "endTime": "09:00",
            "price": "2000"
        }
        {
            "startTime": "10:30",
            "endTime": "20:30",
            "price": "2000"
        }
    ]
}

###
DELETE  http://localhost:5000/api/price/619bacdc7eb3c1e90106768a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTliYTIxM2E2YzhmNzIzOWVlMWYxNjkiLCJyb2xlcyI6WyJDSFVfU0FOIl0sImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2Mzc1OTUyNTIsImV4cCI6MTYzNzY4MTY1Mn0.fNHwSsJOuTVMOVddqnFbvXDcyfPflkwWtSBk5xsMpjQ

###
GET  http://localhost:5000/api/price
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThlMGM1MmEwYjc2ZjY3N2U1ODdlMzgiLCJyb2xlcyI6WyJBRE1JTiIsIktIQUNIX0hBTkciLCJDSFVfU0FOIl0sImlzQWRtaW4iOnRydWUsImlhdCI6MTYzNzE0MDA4MSwiZXhwIjoxNjM3MTQzNjgxfQ.e25-MLU4PhZ7uox8ZqVZf7lXRKSj5IcRoHcnPMzDWaE


