###
POST http://localhost:5000/api/roles
Content-Type: application/json

{
    "name": "Khách hàng"
}

###
GET http://localhost:5000/api/roles


###
GET http://localhost:5000/api/roles/618115740bbf1eee0fbda0b5

###
PUT http://localhost:5000/api/roles/617f7ecf0b4f90e6728cf570
Content-Type: application/json

{
    "name": "Admin"
}

###
DELETE http://localhost:5000/api/roles/618115740bbf1eee0fbda0b5

